services:
  app:
    build: .
    env_file: ./.env
    environment:
      - ENTRYPOINT_FILE=${ENTRYPOINT_FILE}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    ports:
      - 3001:3000
    volumes:
      - .:/app
