services:
  app:
    image: node:22
    working_dir: /app
    build: .
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
    ports:
      - 3000:3000
    volumes:
      - .:/app
